# Generated by Django 3.1.7 on 2021-05-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_subemails_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subemails',
            name='choice',
        ),
    ]
