# Generated by Django 3.1.7 on 2021-05-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_remove_subemails_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subemails',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
