# Generated by Django 3.1.7 on 2021-05-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_auto_20210513_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='subemails',
            name='uuid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
