# Generated by Django 3.1.7 on 2021-05-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0005_subemails_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subemails',
            name='uuid',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
    ]
