# Generated by Django 3.1.7 on 2021-03-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='date',
        ),
    ]
