# Generated by Django 3.1.7 on 2021-03-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_remove_headline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='title2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
