# Generated by Django 3.1.7 on 2021-03-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0003_headline_title2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='head_img',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='headline',
            name='url',
            field=models.URLField(),
        ),
    ]
