# Generated by Django 3.1.7 on 2021-03-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0004_auto_20210320_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='title2',
        ),
    ]
