# Generated by Django 3.1.7 on 2021-04-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0007_auto_20210405_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='ask',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='avg_volume',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='bid',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='current_price',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='day_range',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='earnings_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='market_cap',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='open',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='previous_close',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='volume',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='year_range',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='year_target_est',
            field=models.CharField(max_length=30),
        ),
    ]
