# Generated by Django 3.1.7 on 2021-04-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0011_ticker_tick'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='company_profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
