# Generated by Django 3.1.7 on 2021-04-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0012_ticker_company_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graphs',
        ),
    ]
