# Generated by Django 3.1.7 on 2021-04-14 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0014_headline_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
