# Generated by Django 3.1.7 on 2021-05-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0017_auto_20210502_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='company_logo',
            field=models.URLField(default=1),
        ),
        migrations.AddField(
            model_name='ticker',
            name='company_website',
            field=models.URLField(default=1),
        ),
    ]
