# Generated by Django 3.1.7 on 2021-05-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0019_auto_20210505_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='company_address2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
