# Generated by Django 3.1.7 on 2021-05-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0020_ticker_company_address2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, default=1, null=True)),
            ],
        ),
    ]
