# Generated by Django 3.1.7 on 2021-05-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0021_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='term',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='url',
            field=models.URLField(blank=True, default=1, null=True, unique=True),
        ),
    ]
