# Generated by Django 3.1.7 on 2021-05-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0022_auto_20210510_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
